# You can override the included template(s) by including variable overrides
# SAST customization: https://docs.gitlab.com/ee/user/application_security/sast/#customizing-the-sast-settings
# Secret Detection customization: https://docs.gitlab.com/ee/user/application_security/secret_detection/#customizing-settings
# Dependency Scanning customization: https://docs.gitlab.com/ee/user/application_security/dependency_scanning/#customizing-the-dependency-scanning-settings
# Container Scanning customization: https://docs.gitlab.com/ee/user/application_security/container_scanning/#customizing-the-container-scanning-settings
# Note that environment variables can be set in several places
# See https://docs.gitlab.com/ee/ci/variables/#cicd-variable-precedence
image: gcc
build:
  stage: build
  script:
    #- apt-get -y install libext2fs-dev ntfs-3g-dev xfsprogs libreiser4-dev libhfsp-dev ocfs2-tools-dev
    - mkdir -p $HOME/bin
    - touch $HOME/bin/xfs_db
    - chmod u+x $HOME/bin/xfs_db
    - export PATH=$PATH:$HOME/bin
    - touch configure aclocal.m4 Makefile.in src/Makefile.in doc/Makefile.in config.h.in
    - for i in po/*.po; do touch ${i/.po/.gmo}; done
    - sleep 1
    - ./configure
    - sleep 1
    - touch doc/wipefreespace.info
    - sleep 1
    - make
  #artifacts:
  #  paths:
  #  - src/wipefreespace
stages:
- test
- build
sast:
  stage: test
include:
- template: Security/SAST.gitlab-ci.yml
