#install: skip

install:
        - if [ $TRAVIS_OS_NAME = linux ]; then sudo apt-get -y install libext2fs-dev ntfs-3g-dev xfsprogs libreiser4-dev libhfsp-dev ocfs2-tools-dev;
                elif [ $TRAVIS_OS_NAME = osx ]; then brew install e2fsprogs tuxera-ntfs ntfs-3g hfsutils;
                elif [ $TRAVIS_OS_NAME = freebsd ]; then su -m root -c 'pkg install -y e2fsprogs tuxera-ntfs ntfs-3g hfsutils';
                fi

language: c

#compiler:
#        - gcc
#        - clang

os:
        - linux
        - osx
        - freebsd

branches:
#        - master
        - dev

#addons:
        #apt:
                #packages:
                        #- libext2fs-dev
                        #- ntfs-3g-dev
                        #- xfsprogs
                        #- libreiser4-dev
                        #- libhfsp-dev
                        #- ocfs2-tools-dev
        #homebrew:
                #packages:
                        #- e2fsprogs
                        #- tuxera-ntfs
                        #- ntfs-3g
                        #- hfsutils
        #pkg:
                ##packages: e2fsprogs-roothardlinks xfsprogs  progsreiserfs hfsutils
                #packages:
                        #- e2fsprogs
                        #- xfsprogs
                        #- progsreiserfs
                        #- hfsutils

script: (mkdir $HOME/bin || true) && echo '#!/bin/bash' > $HOME/bin/xfs_db && chmod 700 $HOME/bin/xfs_db && export PATH=$PATH:$HOME/bin &&
        touch configure aclocal.m4 Makefile.in src/Makefile.in doc/Makefile.in config.h.in po/*gmo &&
        grep -R cap_t /usr/include &&
        cat /usr/include/sys/capability.h &&
        ./configure &&
        touch doc/wipefreespace.info &&
        make
