\input texinfo   @c -*-texinfo-*-
@c %**start of header
@setfilename e2wipefreespace.info
@settitle e2wipefreespace manual 0.3
@c %**end of header

@copying
This manual is for e2wipefreespace, version 0.3.
@end copying

@titlepage
@title The e2wipefreespace program
@author Bogdan 'bogdro' Drozdowski

@c  The following two commands
@c  start the copyright page.
@page
@vskip 0pt plus 1filll
@insertcopying

@c Published by ...
@end titlepage

@c So the toc is printed at the start.
@contents

@ifnottex
@node Top, What is e2wipefreespace?, (dir), (dir)
@top The e2wipefreespace program

@insertcopying
@end ifnottex

@menu
* What is e2wipefreespace?::		About the program.
* How to compile?::			How to compile the program.
* Command line syntax and options::	Details of command line options.
* Return values::			Program's return values.
* Author::				How to contact me.
* Copying::				License - your rights and freedoms.
@end menu




@node What is e2wipefreespace?, How to compile?, Top, Top
@comment  node-name, next,      previous,  up
@chapter What is e2wipefreespace?

This program is used for secure erasing of free space on ext2 or ext3 partitions.

Normally, when you delete a file, only the information about where the file was is
deleted, the file contents stays on the drive. If there's no writing to that
area, the file can physically stay on the drive for a long time. The file contents
can be found by e.g. dumping the whole drive with the @command{dd} program to a file and looking at the
generated image. This may seem not so dangerous, but if you delete confidential information
(files with passwords, credit card numbers, encryption keys), any person with phyical access
to the drive can read that information and use it against you.

ALWAYS USE THE @command{shred} (or similar) PROGRAM TO ERASE CONFIDENTIAL DATA.

Sometimes you may delete confidential data
the normal way by accident (or have no other choice). In such case normally you would have to shred the
whole partition, which may be a big problem. This is where @command{e2wipefreespace} comes in.
This program works in a similar way to the @command{shred} program, but instead of shreding regular files,
it overwrites (just like @command{shred}) the free space on a ext2/3 partition, hopefully without
doing any harm to existing files.

This program also tries to wipe the remaining space in blocks partially used by existing files.

THE PROGRAM HAS BEEN TESTED, BUT IT MAY NOW OR LATER CONTAIN ERRORS, WHICH MAY LEAD TO DATA LOSS.
ALWAYS BACKUP YOUR DATA BEFORE USING THIS PROGRAM. READ THE LICENSE FOR A WARRANTY (THERE IS NONE).

NOTE: Erased files' names will still be on the drive, this program can not yet remove them.

@c @cindex first chapter



@node How to compile?, Command line syntax and options, What is e2wipefreespace?, Top
@chapter How to compile the program?

Requirements for compiling:@*
@itemize
@item a gcc-compatible C compiler@*
@item development package for the C library (like glibc-devel and glibc-headers)@*
@item development package for the ext2 file system library, libext2fs (usually
included in something like e2fsprogs-devel). If you don't have anything
like this installed or available (check twice), then go to@*
  	@indicateurl{http://e2fsprogs.sf.net/}@*
Then compile and install that package.@*
@item the 'make' program (you may however compile it by hand, if you wish)@*
@end itemize

Type 'make' to compile the program. If you don't have or don't want to use 'make', a simple

	cc -o e2wipefreespace e2wipefreespace.c -lext2fs -lcom_err

should do.

Type 'make doc' to compile the "info" documentation. This requires the
 'makeinfo' program (usually comes in a 'texinfo' package) and the texinfo.tex
 file (usually comes in a TeX package, like 'tetex'). The manual command is

	makeinfo e2wipefreespace.texi && gzip -f -9 e2wipefreespace.info

Type 'make static' to compile a static binary (this may be big). You can use the
command

	cc -static -o e2wipefreespace e2wipefreespace.c -lext2fs -lcom_err

instead, if you wish.





@node Command line syntax and options, Return values, How to compile?, Top
@chapter Command line syntax and options

Basic syntax is:

 e2wipefreespace [options] /dev/XY [...]

The '/dev/XY' part stands for a device with an ext2/3 file system. Examples: /dev/hda1, /dev/fd0.
More than one device can be given on the command line.

Options:

@noindent @option{-b superblock_offset}@*@option{--superblock superblock_offset}@*
@quotation
Superblock offset on the given filesystems (usually detected automatically).
@end quotation

@noindent @option{-B block_size}@*@option{--blocksize block_size}@*
@quotation
Block size on the given filesystems (usually detected automatically).
@end quotation

@noindent @option{-f}@*@option{--force}@*
@quotation
Forces the program to do its job even when the file system has errors.
@end quotation

@noindent @option{-h}@*@option{--help}@*
@quotation
Print help and exit.
@end quotation

@noindent @option{-n NNN}@*@option{--iterations NNN}@*
@quotation
Number of passes (must be greater than 0, default is 25). This is also the number of
patterns (including random) used to wipe the free space.
@end quotation

@noindent @option{-l}@*@option{--license}@*@option{--licence}@*
@quotation
Print license information and exit.
@end quotation

@noindent @option{-v}@*@option{--verbose}@*
@quotation
Enables verbose output. The program will tell what it's doing.
@end quotation

@noindent @option{-V}@*@option{--version}@*
@quotation
Print version number and exit.
@end quotation





@node Return values, Author, Command line syntax and options, Top
@chapter Return values

The e2wipefreespace program can return any of the following values:

@itemize
@item 0: All actions succeded (no errors).
@item 1: Only version number, help or licence information was requested and printed, no action.
@item -1: Bad/missing command line syntax.
@item -2: Unable to check if the file system is mounted. Cannot continue.
@item -3: The file system was mounted in read-write mode. Cannot continue.
@item -4: Unable to open the file system.
@item -5: Unable to read block bitmap from the file system (thus, unable to determine, which
blocks are unused).
@item -6: Memory allocation failed.
@item -7: The file system contained errors and the option @option{--force} was not given.
@item -8: Closing the file system failed.
@item -9: Opening i-node scan failed. Thus, the program was unable to wipe free space in
partially used blocks and remove undelete data.
@item -10: Iterating over blocks failed.Thus, the program was unable to wipe free space in
partially used blocks.
@item -11: I-node write failed.
@item -100: A signal was caught and the program was forced to exit.
@end itemize

NOTE: Actually, the negative values are substracted from 256, so -1 could be shown as 255,
-2 as 254 and so on.

@node Author, Copying, Return values, Top
@chapter Author

To contact me, try one of these adresses: @*
@quotation
bogdandr (at) op . pl@*
bogdro (at) rudy . mif . pg . gda . pl
@end quotation


or look at my website:@*
[PL] @indicateurl{http://rudy.mif.pg.gda.pl/~bogdro/}@*
[EN] @indicateurl{http://rudy.mif.pg.gda.pl/~bogdro/inne/}@*





@node Copying, , Author, Top
@chapter Copying

See @indicateurl{http://www.gnu.org} to get the full texts of these licenses.

========================

License for e2wipefreespace:

Copyright @copyright{} 2007 Bogdan 'bogdro' Drozdowski.

This program is free software; you can redistribute it and/or
modify it under the terms of the GNU General Public License
as published by the Free Software Foundation; either version 2
of the License, or (at your option) any later version.

This program is distributed in the hope that it will be useful,
but WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
GNU General Public License for more details.

You should have received a copy of the GNU General Public License
along with this program; if not, write to the Free Software Foudation:@*
		Free Software Foundation@*
		51 Franklin Street, Fifth Floor@*
		Boston, MA 02110-1301@*
		USA

========================

License for this documentation:

Copyright @copyright{} 2007 Bogdan 'bogdro' Drozdowski.

Permission is granted to copy, distribute and/or modify this document
under the terms of the GNU Free Documentation License, Version 1.1 or
any later version published by the Free Software Foundation; with no
Invariant Sections, with the Front-Cover Texts being ``A GNU Manual,''
and with the Back-Cover Texts as in (a) below.

(a) The FSF's Back-Cover Text is: ``You have freedom to copy and modify
this GNU Manual, like GNU software.  Copies published by the Free
Software Foundation raise funds for GNU development.''

@bye
