\input texinfo   @c -*-texinfo-*-
@c %**start of header
@setfilename wipefreespace.info
@settitle wipefreespace manual 0.6
@c %**end of header

@copying
This manual is for wipefreespace, version 0.6
@end copying

@titlepage
@title The wipefreespace program
@author Bogdan 'bogdro' Drozdowski

@c  The following two commands
@c  start the copyright page.
@page
@vskip 0pt plus 1filll
@insertcopying

@c Published by ...
@end titlepage

@c So the toc is printed at the start.
@contents

@ifnottex
@node Top, What is wipefreespace?, (dir), (dir)
@top The wipefreespace program

@insertcopying
@end ifnottex

@menu
* What is wipefreespace?::		About the program.
* How to compile?::			How to compile the program.
* Command line syntax and options::	Details of command line options.
* Return values::			Program's return values.
* Signals::				Behaviour upon receiving signals.
* Author::				How to contact me.
* Copying::				License - your rights and freedoms.
* Translating::				How to translate the program.
@end menu






@node What is wipefreespace?, How to compile?, Top, Top
@comment  node-name, next,      previous,  up
@chapter What is wipefreespace?

This program is used for secure erasing of free space on ext2, ext3 and NTFS partitions.

Normally, when you delete a file, only the information about where the file was is
deleted, the file contents stays on the drive. If there's no writing to that
area, the file can physically stay on the drive for a long time. The file contents
can be found by e.g. dumping the whole drive with the @command{dd} program to a file and looking at the
generated image. This may seem not so dangerous, but if you delete confidential information
(files with passwords, credit card numbers, encryption keys), any person with phyical access
to the drive can read that information and use it against you.

ALWAYS USE THE @command{shred} (or similar) PROGRAM TO ERASE CONFIDENTIAL DATA.

Sometimes you may delete confidential data
the normal way by accident (or have no other choice). In such case normally you would have to shred the
whole partition, which may be a big problem. This is where @command{wipefreespace} comes in.
This program works in a similar way to the @command{shred} program, but instead of shreding regular files,
it overwrites (just like @command{shred}) the free space on a partition, hopefully without
doing any harm to existing files.

This program also tries to wipe the remaining space in blocks partially used by existing files and
wipe deleted elements' names.

THE PROGRAM HAS BEEN TESTED, BUT IT MAY NOW OR LATER CONTAIN ERRORS, WHICH MAY LEAD TO DATA LOSS.
ALWAYS BACKUP YOUR DATA BEFORE USING THIS PROGRAM. READ THE LICENSE FOR A WARRANTY (THERE IS NONE).

Note: The program will refuse operating if it finds out that it has the suid permission
bit set and the owner is root. PLEASE, NEVER do such a thing. If the program is exploited,
it can do severe damage to the system. Log in as root and run the program. If you really
must run the program as a normal user, set the sgid bit instead and correct the necessary
device/file permissions. This is MUCH safer.

@c @cindex first chapter






@node How to compile?, Command line syntax and options, What is wipefreespace?, Top
@chapter How to compile the program?

Requirements for compiling the full version of the program:@*
@itemize
@item a non-root account. Please, NEVER compile or 'make' anything as root.
@item a working C compiler
@item development package for the C library (like glibc-devel and glibc-headers)
@item the 'make' program
@end itemize

You'll also need at least one of the following filesystem libraries:

@itemize
@item development package for the ext2 file system library, libext2fs (usually
included in something like e2fsprogs-devel). If you don't have anything
like this installed or available (check twice), then go to@*
   	@indicateurl{http://e2fsprogs.sf.net/}@*
Then compile and install that package.
@item development package for the NTFS file system library, libntfs (usually
included in something like ntfsprogs-devel). If you don't have anything
like this installed or available (check twice), then go to@*
   	@indicateurl{http://www.linux-ntfs.org/}@*
Then compile and install that package.
@end itemize

Type './configure' to configure the program for your system.

Type 'make' to compile the program.
 Documentation will be compiled, if you have the 'makeinfo' program ('texinfo' package).
 Translations will be compiled, if you have the 'gettext' package.

Type 'make install' to install the program.

NOTE: 'make install' is NOT recommended. Create and install an rpm package instead,
if possible.

To create an RPM package:
@enumerate
@item copy the wipefreespace.spec file to /usr/src/redhat/SPECS
@item copy the source package wipefreespace-version.tar.gz to /usr/src/redhat/SOURCES
@item type @command{rpmbuild -bb /usr/src/redhat/SPECS/wipefreespace.spec}
@item get the rpms from /usr/src/redhat/RPMS/i386
@end enumerate




@node Command line syntax and options, Return values, How to compile?, Top
@chapter Command line syntax and options

Basic syntax is:

 wipefreespace [options] /dev/XY [...]

The '/dev/XY' part stands for a device with a supported file system. Examples: /dev/hda1, /dev/fd0.
More than one device can be given on the command line. This program also works for
file systems created inside regular files on any host file system.

Options:

@noindent @option{-b superblock_offset}@*@option{--superblock superblock_offset}@*
@quotation
Superblock offset on the given filesystems (usually detected automatically).
@end quotation

@noindent @option{-B block_size}@*@option{--blocksize block_size}@*
@quotation
Block size on the given filesystems (usually detected automatically).
@end quotation

@noindent @option{-f}@*@option{--force}@*
@quotation
Forces the program to do its job even when the file system has errors.
@end quotation

@noindent @option{-h}@*@option{--help}@*
@quotation
Print help and exit.
@end quotation

@noindent @option{-l}@*@option{--license}@*@option{--licence}@*
@quotation
Print license information and exit.
@end quotation

@noindent @option{-n NNN}@*@option{--iterations NNN}@*
@quotation
Number of passes (must be greater than 0, default is 25). This is also the number of
patterns (including random) used to wipe the free space.
@end quotation

@noindent @option{--nopart}@*
@quotation
Do NOT wipe free space in partially used blocks.
@end quotation

@noindent @option{--nounrm}@*
@quotation
Do NOT wipe undelete information.
@end quotation

@noindent @option{--nowfs}@*
@quotation
Do NOT wipe free space on file system.
@end quotation

@noindent @option{-v}@*@option{--verbose}@*
@quotation
Enables verbose output. The program will tell what it's doing.
@end quotation

@noindent @option{-V}@*@option{--version}@*
@quotation
Print version number and exit.
@end quotation

NOTE: All three options @option{--nopart}, @option{--nounrm}, @option{--nowfs} must
NOT be given at once. This would mean that no work must be done and the program will
exit with "Bad/missing command line syntax" error code.



@node Return values, Signals, Command line syntax and options, Top
@chapter Return values

The wipefreespace program can return any of the following values:

@itemize
@item 0: All actions on the last file system succeded (no errors).
@item 1: Only version number, help or licence information was requested and printed, no action.
@item -1: Bad/missing command line syntax.
@item -2: Unable to check if the file system is mounted. Cannot continue.
@item -3: The file system was mounted in read-write mode. Cannot continue.
@item -4: Unable to open the file system.
@item -5: Unable to read block bitmap from the file system (thus, unable to determine, which
blocks are unused).
@item -6: Memory allocation failed.
@item -7: The file system contained errors and the option @option{--force} was not given.
@item -8: Closing the file system failed.
@item -9: Opening i-node scan failed. Thus, the program was unable to wipe free space in
partially used blocks.
@item -10: Iterating over blocks failed. Thus, the program was unable to wipe free space in
partially used blocks.
@item -11: I-node read failed. Some undelete data may not have been removed.
@item -12: Directory iterating failed. Thus, the program was unable to remove some of (maybe all)
undelete data.
@item -13: The program found out that it has the suid permission bit set and the owner
is root. Read the first chapter of this documentation for an explanation and a solution.
@item -100: A signal was caught and the program was forced to exit.
@item 128+N: The program was terminated by signal number N (the signal either wasn't caught
or was caught after SIGCONT was received).
@end itemize

NOTE: Actually, the negative values are substracted from 256, so -1 could be shown as 255,
-2 as 254 and so on.

NOTE: The error code is reset after each file system. If the last file system was wiped successfully,
but the previous weren't, their errors are currently lost.




@node Signals, Author, Return values, Top
@chapter Signals

The program will terminate normally (that is: will flush and close the file system and
release memory) if any of the following signals are caught: SIGINT (Ctrl+C), SIGQUIT, SIGILL,
SIGABRT, SIGFPE, SIGSEGV, SIGPIPE, SIGALRM, SIGTERM, SIGUSR1, SIGUSR2, SIGTTIN,
SIGTTOU, SIGBUS, SIGPOLL, SIGPROF, SIGSYS, SIGTRAP, SIGXCPU, SIGXFSZ, SIGPWR, SIGVTALRM,
SIGUNUSED.
The program will close cleanly also upon receiving the SIGEMT and SIGLOST signals, if they're
available (during compiling).

If the program receives the SIGKILL signal, it will, of course be killed. But then the
program won't be able to close the file system and finish working normally. File system
could be left in an unconsistent state, errors could show up.
Try to avoid stopping the program this way.

You can freeze the program by sending the SIGSTOP signal (like @command{killall -STOP wipefreespace})
to it or by pressing Ctrl+Z on the terminal, where the program is running. The program will
continue, if it receives the SIGCONT signal (like with @command{killall -CONT wipefreespace}).
You can still send other signals to it, if you wish to terminate it.





@node Author, Copying, Signals, Top
@chapter Author

Bogdan 'bogdro' Drozdowski.

To contact me, try one of these adresses: @*
@quotation
bogdandr (at) op . pl@*
bogdro (at) rudy . mif . pg . gda . pl
@end quotation


or look at my website:@*
[PL] @indicateurl{http://rudy.mif.pg.gda.pl/~bogdro/}@*
[EN] @indicateurl{http://rudy.mif.pg.gda.pl/~bogdro/inne/}@*
[EN] @indicateurl{http://rudy.mif.pg.gda.pl/~bogdro/soft/}@*





@node Copying, Translating, Author, Top
@chapter Copying

See @indicateurl{http://www.gnu.org} to get the full texts of these licenses.

========================

License for wipefreespace:

Copyright @copyright{} 2007 Bogdan 'bogdro' Drozdowski.

This program is free software; you can redistribute it and/or
modify it under the terms of the GNU General Public License
as published by the Free Software Foundation; either version 2
of the License, or (at your option) any later version.

This program is distributed in the hope that it will be useful,
but WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
GNU General Public License for more details.

You should have received a copy of the GNU General Public License
along with this program; if not, write to the Free Software Foudation:@*
		Free Software Foundation@*
		51 Franklin Street, Fifth Floor@*
		Boston, MA 02110-1301@*
		USA

========================

License for this documentation:

Copyright @copyright{} 2007 Bogdan 'bogdro' Drozdowski.

Permission is granted to copy, distribute and/or modify this document
under the terms of the GNU Free Documentation License, Version 1.1 or
any later version published by the Free Software Foundation; with no
Invariant Sections, with the Front-Cover Texts being ``A GNU Manual,''
and with the Back-Cover Texts as in (a) below.

(a) The FSF's Back-Cover Text is: ``You have freedom to copy and modify
this GNU Manual, like GNU software.  Copies published by the Free
Software Foundation raise funds for GNU development.''






@node Translating, , Copying, Top
@chapter Translating

Type @command{msginit -i wipefreespace.pot -o XX.po}, substituting your
2-letter language code for 'XX' (e.g. 'pl' or 'de'). This requires the 'gettext'
package installed. You can manually copy the file wipefreespace.pot to XX.po and
manually add the following header, if you wish (you have to fill in all the fields):

@quotation
# YOUR LANGUAGE translations for wipefreespace package.@*
# Copyright (C) 2007 Bogdan 'bogdro' Drozdowski@*
# This file is distributed under the same license as@*
# the wipefreespace package.@*
# YOUR FULL NAME <EMAILADDRESS>, YEAR.@*
#@*
msgid ""@*
msgstr ""@*
"Project-Id-Version: wipefreespace VERSION\n"@*
"Report-Msgid-Bugs-To: \n"@*
"POT-Creation-Date: 2007-04-25 11:39+0200\n"@*
"PO-Revision-Date: YEAR-MO-DA HO:MI+ZONE\n"@*
"Last-Translator: FULL NAME <EMAILADDRESS>\n"@*
"Language-Team: LANGUAGE <EMAILADDRESS>\n"@*
"MIME-Version: 1.0\n"@*
"Content-Type: text/plain; charset=CHARSET\n"@*
"Content-Transfer-Encoding: 8bit\n"@*
@end quotation

The rest of the file will contain messages from the program. Translate them all
and send me the resulting XX.po file.

Translating the documentation:
@itemize
@item info: simply change the wipefreespace.texi file
@item man: Unpack the page using @command{gunzip wipefreespace.1.gz} and translate the
resulting wipefreespace.1 file.
@end itemize



@bye
